print("At 8:00 AM I wake up and brush my teeth and shower")
print("At 8:30 AM I have breakfast")
print("At 9:00 AM I study for 2 hours")
print("At 11:00 AM I take a break")
print("At 11:30 AM I prepare for coding class")
print("At 12:00 PM I attend coding class")
print("At 1:00 PM I have lunch")
print("At 2:00 PM I play online with my friends")
print("At 5:00 PM I go outside to play football with my friends")
print("At 8:00 PM I come back home and have dinner")
print("At 9:00 PM I sleep and rest for the next day")
